#! /bin/sh

INSTALL_DIR=/opt/datadog-agent
LOG_DIR=/var/log/datad
mkdir -p $LOG_DIR

# Just in case there are leftovers from previous installation (we are now using our own
# supervisord)
KNOWN_LINUX_DISTRIBUTION="(Debian|Ubuntu|RedHat|CentOS|openSUSE|Amazon)"
LINUX_DISTRIBUTION=$(lsb_release -d 2>/dev/null | grep -Eo $KNOWN_LINUX_DISTRIBUTION  || grep -Eo $KNOWN_DISTRIBUTION /etc/issue 2>/dev/null || uname -s)

# Linux installation
if [$DISTRIBUTION != "Darwin"]; then
  if [ -f /etc/debian_version ] || [ "$DISTRIBUTION" == "Debian" ] || [ "$DISTRIBUTION" == "Ubuntu" ]; then
    set -e
    if [ -f /etc/init.d/datadog-agent ]; then
        if command -v invoke-rc.d >/dev/null 2>&1; then
            invoke-rc.d datadog-agent stop || true
        else
            /etc/init.d/datadog-agent stop || true
        fi
    fi

    # Since we now package our own supervisor config, we no longer want
    # the old config to be loaded. Since supervisor automatically loads
    # configs in conf.d, we have to delete the old config file.
    if [ -f /etc/supervisor/conf.d/ddagent.conf ]; then
        echo "Removing old configuration from system supervisord"
        rm /etc/supervisor/conf.d/ddagent.conf
    fi

    # Previous versions of dd-agent created this file but didn't do
    # anything with it.
    if [ -f /etc/dd-agent/supervisor_ddagent.conf ]; then
        rm /etc/dd-agent/supervisor_ddagent.conf
    fi

    #DEBHELPER#

  elif [ -f /etc/redhat-release ] || [ -f /etc/system-release ] || [ "$LINUX_DISTRIBUTION" == "RedHat" ] || [ "$LINUX_DISTRIBUTION" == "CentOS" ] || [ "$LINUX_DISTRIBUTION" == "openSUSE" ] || [ "$LINUX_DISTRIBUTION" == "Amazon" ]; then
      getent group dd-agent >/dev/null || groupadd -r dd-agent
      getent passwd dd-agent >/dev/null || \
          useradd -r -M -g dd-agent -d /opt/datadog-agent -s /bin/sh \
          -c "Datadog Agent" dd-agent

      grep -q "datadog" /etc/supervisord.conf
      if [ $? -eq 0 ]
        then
        echo -n "Removing old configuration from system supervisord"
         if [ -x "/usr/bin/supervisorctl" ]; then
              supervisorctl stop collector
              supervisorctl stop forwarder
         fi

        /opt/datadog-agent/setup-supervisor.py /etc/dd-agent/supervisor.conf /etc/supervisord.conf remove
        rm /opt/datadog-agent/setup-supervisor.py
      fi

  else
      echo "[ ${Red}FAILED ${RCol}]\tYour system is currently not supported by this script.";
      exit 1;
  fi
elif [$DISTRIBUTION = "Darwin"]; then
    APP_CONF_DIR="/Applications/Datadog Agent.app/Contents/Resources"

    LOG_FILE="$LOG_DIR/preinstall.log"
    exec > $LOG_FILE 2>&1

    if [ -e "$APP_CONF_DIR/datadog.conf" ]; then
	  # Stop old version
          "$APP_CONF_DIR/../MacOS/datadog-agent" stop || true
          kill `ps aux | grep 'Datadog Agent.app' | grep -v grep  | cut -d ' ' -f 4` || true

          # Save old conf
          mkdir -p /tmp/conf.d
          rm -rf /tmp/checks.d
          rm -f /tmp/datadog.conf /tmp/conf.d/*
	  cp -f "$APP_CONF_DIR/datadog.conf" /tmp
	  cp -f "$APP_CONF_DIR/conf.d/"*.yaml /tmp/conf.d
	  cp -fR "$APP_CONF_DIR/checks.d" /tmp/
 	fi

 	# Clean before install
    rm -rf $INSTALL_DIR
    rm -f /usr/local/bin/datadog-agent
fi

# Delete .pyc files
# FIXME: it shouldn't be done there, but only in prerm (see 6.6
# of https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html)
# It is also here because version < 5.4 didn't delete .pyc,
# so we need to be sure to clean them here (if a file is deleted for instance)
find /opt/datadog-agent/agent -name '*.py[co]' -type f -delete || true

# FIXME: remove when CentOS5 support is dropped (03/31/2017) or when everybody
# has stopped using dd-agent 5.3 (and older versions ofc)
rm -f /opt/datadog-agent/agent/checks/utils.py

exit 0
