#!/bin/bash -e

####################
# Set up defaults
###################

: ${DISTRO:?"Need to set DISTRO"}
: ${ARCH:?"Need to set ARCH"}

# Defaults for jenkins builds and local builds

if [ -z "$JENKINS" ]; then
    echo "LOCAL build"
    export LOG_LEVEL="debug"
else
    echo "JENKINS build"
    export LOG_LEVEL="info"
    export OMNIBUS_APPEND_TIMESTAMP="false"
fi

LOG_FILE=`mktemp -t ddagentomnibus_${DISTRO}_${ARCH}.XXXXXXX`

####################
# Helper functions
###################

reload_and_provision() {
    vagrant reload --provision $DISTRO-$ARCH 2>&1 | tee -a $LOG_FILE
    # If VM is not present, create it with `up`, `reload` never creates
    if grep -q "VM not created" $LOG_FILE; then
        echo "Berkshelf error, trying to reload the VM"
        vagrant up --provision $DISTRO-$ARCH 2>&1 | tee -a $LOG_FILE
    fi
}
destroy() {
    vagrant destroy -f $DISTRO-$ARCH 2>&1 | tee -a $LOG_FILE
}

####################
# Script
###################

if [ ! -z "$FORCE_DESTROY" ]; then
    destroy
fi

reload_and_provision

# Known bug, reload and retry
# https://github.com/berkshelf/vagrant-berkshelf/issues/78
if grep -q "You must specify at least one cookbook" $LOG_FILE; then
    echo "Berkshelf error, trying to reload the VM"
    reload_and_provision
fi
