source 'https://rubygems.org'
gem 'omnibus', :git => 'git://github.com/datadog/omnibus-ruby.git', :branch => 'etienne/ship-licenses-and-sources'
gem 'omnibus-software', git: 'git://github.com/datadog/omnibus-software.git', branch: 'etienne/omnibus-4-osx'
gem 'fpm', '~> 1.2.0'
gem 'httparty'
