source 'https://rubygems.org'
gem 'omnibus', git: 'git://github.com/datadog/omnibus-ruby.git', branch: 'etienne/windows'
gem 'omnibus-software', git: 'git://github.com/datadog/omnibus-software.git', branch: 'etienne/windows'
gem 'win32-process', '~> 0.7.1'
gem 'windows-pr', '~> 1.2.2'
gem 'win32-api'
