source 'https://rubygems.org'
#gem 'omnibus', :git => 'git://github.com/datadog/omnibus-ruby.git', :branch => 'v3.2.2'
gem 'omnibus', :git => 'git://github.com/datadog/omnibus-ruby.git', :branch => 'custom3.2.2-2'
gem 'omnibus-software', :git => 'git://github.com/datadog/omnibus-software.git', :branch => '3.2'
gem 'fpm', '~> 1.2.0'
