#!/bin/sh
LINUX_DISTRIBUTION=$(grep -Eo "(Debian|Ubuntu|RedHat|CentOS|openSUSE|Amazon)" /etc/issue)

if [ -f "/etc/debian_version" ] || [ "$LINUX_DISTRIBUTION" == "Debian" ] || [ "$LINUX_DISTRIBUTION" == "Ubuntu" ]; then
    set -e

    if [ "$1" = purge ]; then
        deluser netsil-dd-agent
        # luhkevin
        rm -rf /opt/netsil/collectors
        rm -rf /var/log/netsil /var/log/netsil-collectors.log
        rm -rf /var/log/netsil-datadog
        rm -rf /etc/netsil-dd-agent
    fi
elif [ -f "/etc/redhat-release" ] || [ "$LINUX_DISTRIBUTION" == "RedHat" ] || [ "$LINUX_DISTRIBUTION" == "CentOS" ] || [ "$LINUX_DISTRIBUTION" == "openSUSE" ] || [ "$LINUX_DISTRIBUTION" == "Amazon" ]; then
    case "$*" in
      0)
        # We're uninstalling.
        getent passwd netsil-dd-agent > /dev/null && userdel netsil-dd-agent
        getent group netsil-dd-agent >/dev/null && groupdel netsil-dd-agent
        ;;
      1)
        # We're upgrading.
        ;;
      *)
        ;;
    esac
else
      echo "[ ${Red}FAILED ${RCol}]\tYour system is currently not supported by this script.";
      exit 1;
fi
exit 0
