#! /bin/sh
LINUX_DISTRIBUTION=$(grep -Eo "(Debian|Ubuntu|RedHat|CentOS|openSUSE|Amazon)" /etc/issue)

remove_py_compiled_files()
{
    # Delete all the .pyc files in the embedded dir that are part of the agent's package
    if [ -f "/opt/netsil/collectors/embedded/.py_compiled_files.txt" ]; then
        # (commented lines are filtered out)
        cat /opt/netsil/collectors/embedded/.py_compiled_files.txt | grep -v '^#' | xargs rm -f
    fi
}


if [ -f "/etc/debian_version" ] || [ "$LINUX_DISTRIBUTION" == "Debian" ] || [ "$LINUX_DISTRIBUTION" == "Ubuntu" ]; then
    if command -v invoke-rc.d >/dev/null 2>&1; then
        invoke-rc.d netsil-datadog-agent stop || true

        # Removing the service form startup (since it's not there anymore)
        update-rc.d -f netsil-datadog-agent disable >/dev/null 2>&1
        update-rc.d -f netsil-datadog-agent remove
    else
        /etc/init.d/netsil-datadog-agent stop || true
    fi

    remove_py_compiled_files
elif [ -f "/etc/redhat-release" ] || [ "$LINUX_DISTRIBUTION" == "RedHat" ] || [ "$LINUX_DISTRIBUTION" == "CentOS" ] || [ "$LINUX_DISTRIBUTION" == "openSUSE" ] || [ "$LINUX_DISTRIBUTION" == "Amazon" ]; then
    case "$*" in
          0)
            # We're uninstalling.
            /etc/init.d/netsil-datadog-agent stop

            remove_py_compiled_files
            ;;
          1)
            # We're upgrading. Do nothing.
            # The preinst script has taken care of removing the .pyc/.pyo files
            ;;
          *)
            ;;
    esac
else
    echo "[ ${Red}FAILED ${RCol}]\tYour system is currently not supported by this script.";
    exit 1;
fi

# Delete all.pyc files in the agent's dir
find /opt/netsil/collectors/agent -name '*.py[co]' -type f -delete || echo 'Unable to delete .pyc files'

##########################
### Netsil pre-rm code ###
##########################
if [ -x "/opt/netsil/collectors/stop.sh" ] ; then
   /opt/netsil/collectors/stop.sh
else
   echo "Stop script for netsil collectors does not exist or is not executable"
fi

exit 0
